-- Generated by Tools/GeneratePoisonData.mjs from Forever 1.60.1.70170 game data. Do not edit by hand.
-- Rogue weapon poisons by family, lowest rank first. level: required level to use the item.
-- spell: the item's use spell, which applies the poison. enchant: the weapon enchant it leaves.
-- recipe: the Poisons skill spell that makes it (nil when nothing makes it).
local _,E=...
E.PoisonData={build="1.60.1.70170",families={
 {key="crippling",name="Crippling Poison",ranks={
  {item=3775,level=20,spell=3408,enchant=22,recipe=3420},
  {item=3776,level=50,spell=11202,enchant=603,recipe=3421},
 }},
 {key="instant",name="Instant Poison",ranks={
  {item=6947,level=20,spell=8679,enchant=323,recipe=8681},
  {item=6949,level=28,spell=8686,enchant=324,recipe=8687},
  {item=6950,level=36,spell=8688,enchant=325,recipe=8691},
  {item=8926,level=44,spell=11338,enchant=623,recipe=11341},
  {item=8927,level=52,spell=11339,enchant=624,recipe=11342},
  {item=8928,level=60,spell=11340,enchant=625,recipe=11343},
 }},
 {key="numbing",name="Mind-numbing Poison",ranks={
  {item=5237,level=24,spell=5761,enchant=35,recipe=5763},
  {item=6951,level=38,spell=8693,enchant=23,recipe=8694},
  {item=9186,level=52,spell=11399,enchant=643,recipe=11400},
 }},
 {key="deadly",name="Deadly Poison",ranks={
  {item=2892,level=30,spell=2823,enchant=7,recipe=2835},
  {item=2893,level=38,spell=2824,enchant=8,recipe=2837},
  {item=8984,level=46,spell=11355,enchant=626,recipe=11357},
  {item=8985,level=54,spell=11356,enchant=627,recipe=11358},
  {item=20844,level=60,spell=25351,enchant=2630,recipe=25347},
 }},
 {key="wound",name="Wound Poison",ranks={
  {item=10918,level=32,spell=13219,enchant=703,recipe=13220},
  {item=10920,level=40,spell=13225,enchant=704,recipe=13228},
  {item=10921,level=48,spell=13226,enchant=705,recipe=13229},
  {item=10922,level=56,spell=13227,enchant=706,recipe=13230},
 }},
}}
