-- The class quotes the user approved on 2026-09-30, frozen word for word and in
-- order for TestAFKScreen: Modules/AFKQuotes.lua must match them exactly (text,
-- speaker, where). Change a line here only for a change the user approved.
return {
 {"WARRIOR",{
  {"Warriors, I know you can hit harder than that! Let's see it!","Nefarian","Blackwing Lair"},
  {"Ah - I've been waiting for a real challenge!","Herod","Scarlet Monastery"},
  {"You're a lot tougher than you look!","Bartleby","Quest: Beat Bartleby"},
  {"Have a drink, and savor it... because it might be your last.","Yorus Barleybrew","Quest: Yorus Barleybrew"},
  {"We are the shield of the Horde, and we keep our weaker brethren safe.","Uzzek","Quest: Path of Defense"},
  {"But you are a warrior, and you will triumph or perish trying.","Fallen Hero","Quest: War on the Shadowsworn"},
  {"I see fire in your eyes.","Bath'rah","Quest: The Windwatcher"},
 }},
 {"PALADIN",{
  {"The Light knows no bounds.","Tirion Fordring","Quest: Of Lost Honor"},
  {"Take solace in knowing that the Order is reborn.","Tirion Fordring","Quest: In Dreams"},
  {"Face me, coward. Face the faith and strength that you once embodied.","Tirion Fordring","Hearthglen, Quest: In Dreams"},
  {"Infidels! They must be purified!","Mograine","Scarlet Monastery"},
  {"Kneel! Kneel before the Ashbringer!","Scarlet Monk","Scarlet Monastery"},
  {"At long last, your time has come!","Grayson Shadowbreaker","Quest: The Divination Scryer"},
  {"Congratulations, and may the Light protect you.","Duthorian Rall","Quest: The Tome of Nobility"},
 }},
 {"HUNTER",{
  {"Release the hounds!","Houndmaster Loksey","Scarlet Monastery"},
  {"May your arrows strike true.","Hastat the Ancient","Quest: Ancient Sinew Wrapped Lamina"},
  {"Kill King Bangalash and your hunting prowess is proven to be second to none.","Hemet Nesingwary","Quest: Big Game Hunter"},
  {"What a wonderful day to be alive!","Simone","Un'Goro Crater"},
  {"May the blessings of the Earthmother guide you in choosing a pet.","Yaw Sharpmane","Quest: Taming the Beast"},
  {"Use your new skills with pride; you have earned them.","Dazalar","Quest: Taming the Beast"},
  {"Da path of da hunter is one of our oldest walks of life.","Jen'shan","Quest: Etched Tablet"},
 }},
 {"ROGUE",{
  {"None may challenge the Brotherhood!","VanCleef","The Deadmines"},
  {"You won't see us coming but you'll feel it when we get there...","Mathias Shaw","Quest: Snatch and Grab"},
  {"Ravenholdt has taken an interest in you, young thief.","Fahrad","Quest: The Manor, Ravenholdt"},
  {"Consider yourself the newest member of the Shattered Hand.","Therzok","Quest: The Shattered Hand"},
  {"Being a field agent of the Shattered Hand is dangerous work.","Shenthul","Quest: Mission: Possible But Not Probable"},
  {"Looks can be deceiving though, right?","Marion Call","Quest: Mennet Carkad"},
  {"Keep your eyes peeled for thieves.","Defias Traitor","Westfall"},
 }},
 {"PRIEST",{
  {"Arise, my champion!","Whitemane","Scarlet Monastery"},
  {"Mograine has fallen? You shall pay for this treachery!","Whitemane","Scarlet Monastery"},
  {"Battle with honor. Harness the Light.","Eris Havenfire","Quest: A Warning"},
  {"Tendrils of light escape her hands, cutting through undead by the hundreds.","The Eye of Divinity","Molten Core, item text"},
  {"But before you can know the dark, you must also know the light.","Dark Cleric Beryl","Quest: Garments of Darkness"},
  {"You got the Light inside you, that's for sure.","Maxan Anvol","Quest: Garments of the Light"},
  {"Bethekk, your priestess calls upon your might!","Arlokk","Zul'Gurub"},
 }},
 {"SHAMAN",{
  {"Patience is earth's greatest virtue.","Canaga Earthcaller","Quest: Call of Earth"},
  {"It is the cycle of things. Mountains become deserts. Rivers become canyons.","Seer Ravenfeather","Quest: Call of Earth"},
  {"I see it in your eyes already, the burning, the desire.","Kranal Fiss","Quest: Call of Fire"},
  {"Water be in ya future, mon.","Searn Firewarder","Quest: Call of Water"},
  {"Be bathed in my power! Drink in my might!","Thrall","Quest: For The Horde!"},
  {"Today, you will meet your ancestors!","Drek'Thar","Alterac Valley"},
  {"BY FIRE BE PURGED!","Ragnaros","Molten Core"},
 }},
 {"MAGE",{
  {"Mages too? You should be more careful when you play with magic...","Nefarian","Blackwing Lair"},
  {"This place is under my protection. The mysteries of the arcane shall remain inviolate.","Azuregos","Azshara"},
  {"You, too, shall serve!","Arugal","Shadowfang Keep"},
  {"You will not defile these mysteries!","Arcanist Doan","Scarlet Monastery"},
  {"Magic is powerful. Magic is corrupting. Magic is addicting.","Khelden Bremen","Glyphic Letter"},
  {"We are the ones who control our fate.","Isabella","Glyphic Scroll"},
  {"I had forgotten about that little curse I put on Johnson.","Magus Tirth","Quest: Get the Scoop"},
 }},
 {"WARLOCK",{
  {"For the Legion! For Kil'jaeden!","Lord Kazzak","Blasted Lands"},
  {"Silence, servant! Vengeance will be mine! Death to Stormwind! Death by chicken!","Niby the Almighty","Felwood"},
  {"Don't tell anyone this but Niby is daft.","Impsy","Quest: Flawless Fel Essence"},
  {"When power is concerned, you are drawn in like a moth to the flame.","Strahad Farsan","Quest: Summon Felsteed"},
  {"I summon demons from the Twisting Nether at my leisure.","Nartok","Tainted Parchment"},
  {"So few warlocks remain... We risk much, but the risks are warranted.","Gan'rul Bloodeye","Quest: Creature of the Void"},
  {"Face the true might of the Nathrezim!","Balnazzar","Stratholme"},
 }},
 {"DRUID",{
  {"I AM AWAKE, AT LAST!","Naralex","Wailing Caverns"},
  {"You will never wake the dreamer!","Lord Cobrahn","Wailing Caverns"},
  {"Within the Dream we fight a new foe, born of an ancient evil.","Malfurion Stormrage","Quest: Waking Legends"},
  {"Fiend! Face the might of Cenarius!","Keeper Remulos","Quest: The Nightmare Manifests"},
  {"The strands of LIFE have been severed! The Dreamers must be avenged!","Ysondre","Dragons of Nightmare"},
  {"Inside each of Cenarius' children is the call to serve nature.","Druid trainer","Quest: Heeding the Call"},
  {"To keep the balance is not to be complacent or banal.","Great Bear Spirit","Moonglade"},
 }},
 {"GENERAL",{
  {"The drums of war thunder once again.","Narrator","The intro cinematic"},
  {"TOO SOON! YOU HAVE AWAKENED ME TOO SOON, EXECUTUS!","Ragnaros","Molten Core"},
  {"How fortuitous. Usually, I must leave my lair in order to feed.","Onyxia","Onyxia's Lair"},
  {"In this world where time is your enemy, it is my greatest ally.","Victor Nefarius","Blackwing Lair"},
  {"Your friends will abandon you.","C'Thun","Ahn'Qiraj"},
  {"A huge gnoll, Hogger, is prowling the woods in southwestern Elwynn.","Wanted Poster","Quest: Wanted: \"Hogger\""},
  {"Have you found any sign of her at all?","Mankrik","Quest: Lost in Battle"},
  {"You no take candle!","Kobolds","Elwynn Forest"},
 }},
}
